# Generated by Django 2.1.5 on 2022-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GACourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=75, unique=True)),
                ('startDate', models.DateField()),
                ('courseDescription', models.CharField(max_length=1000)),
            ],
        ),
    ]
